# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: CalemYoung.Dash
PackageVersion: 2.10.2
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{88DC9BD4-16FC-452E-87DD-4B0F54603ED1}}_is1'
AppsAndFeaturesEntries:
- DisplayName: Dash
  Publisher: Calem Young
  DisplayVersion: 2.10.2
  ProductCode: '{88DC9BD4-16FC-452E-87DD-4B0F54603ED1}}_is1'
ReleaseDate: 2026-09-24
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CalemYoung/Dash/releases/download/v2.10.2/DashSetup-2.10.2.exe
  InstallerSha256: E02C663DC062B93F67BBC0CF2B6DB5BC472A736FD0253F96B7CB87FA2D062F02
ManifestType: installer
ManifestVersion: 1.6.0
